// Code generated by MockGen. DO NOT EDIT.
// Source: workflows/subscription/my_service.go

// Package subscription is a generated GoMock package.
package subscription

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMyService is a mock of MyService interface.
type MockMyService struct {
	ctrl     *gomock.Controller
	recorder *MockMyServiceMockRecorder
}

// MockMyServiceMockRecorder is the mock recorder for MockMyService.
type MockMyServiceMockRecorder struct {
	mock *MockMyService
}

// NewMockMyService creates a new mock instance.
func NewMockMyService(ctrl *gomock.Controller) *MockMyService {
	mock := &MockMyService{ctrl: ctrl}
	mock.recorder = &MockMyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMyService) EXPECT() *MockMyServiceMockRecorder {
	return m.recorder
}

// chargeUser mocks base method.
func (m *MockMyService) chargeUser(email, customerId string, amount int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "chargeUser", email, customerId, amount)
}

// chargeUser indicates an expected call of chargeUser.
func (mr *MockMyServiceMockRecorder) chargeUser(email, customerId, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "chargeUser", reflect.TypeOf((*MockMyService)(nil).chargeUser), email, customerId, amount)
}

// sendEmail mocks base method.
func (m *MockMyService) sendEmail(recipient, subject, content string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "sendEmail", recipient, subject, content)
}

// sendEmail indicates an expected call of sendEmail.
func (mr *MockMyServiceMockRecorder) sendEmail(recipient, subject, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "sendEmail", reflect.TypeOf((*MockMyService)(nil).sendEmail), recipient, subject, content)
}
