// Code generated by MockGen. DO NOT EDIT.
// Source: workflows/service/my_service.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMyService is a mock of MyService interface.
type MockMyService struct {
	ctrl     *gomock.Controller
	recorder *MockMyServiceMockRecorder
}

// MockMyServiceMockRecorder is the mock recorder for MockMyService.
type MockMyServiceMockRecorder struct {
	mock *MockMyService
}

// NewMockMyService creates a new mock instance.
func NewMockMyService(ctrl *gomock.Controller) *MockMyService {
	mock := &MockMyService{ctrl: ctrl}
	mock.recorder = &MockMyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMyService) EXPECT() *MockMyServiceMockRecorder {
	return m.recorder
}

// CallAPI1 mocks base method.
func (m *MockMyService) CallAPI1(data string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CallAPI1", data)
}

// CallAPI1 indicates an expected call of CallAPI1.
func (mr *MockMyServiceMockRecorder) CallAPI1(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallAPI1", reflect.TypeOf((*MockMyService)(nil).CallAPI1), data)
}

// CallAPI2 mocks base method.
func (m *MockMyService) CallAPI2(data string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CallAPI2", data)
}

// CallAPI2 indicates an expected call of CallAPI2.
func (mr *MockMyServiceMockRecorder) CallAPI2(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallAPI2", reflect.TypeOf((*MockMyService)(nil).CallAPI2), data)
}

// CallAPI3 mocks base method.
func (m *MockMyService) CallAPI3(data string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CallAPI3", data)
}

// CallAPI3 indicates an expected call of CallAPI3.
func (mr *MockMyServiceMockRecorder) CallAPI3(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallAPI3", reflect.TypeOf((*MockMyService)(nil).CallAPI3), data)
}

// CallAPI4 mocks base method.
func (m *MockMyService) CallAPI4(data string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CallAPI4", data)
}

// CallAPI4 indicates an expected call of CallAPI4.
func (mr *MockMyServiceMockRecorder) CallAPI4(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallAPI4", reflect.TypeOf((*MockMyService)(nil).CallAPI4), data)
}

// ChargeUser mocks base method.
func (m *MockMyService) ChargeUser(email, customerId string, amount int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ChargeUser", email, customerId, amount)
}

// ChargeUser indicates an expected call of ChargeUser.
func (mr *MockMyServiceMockRecorder) ChargeUser(email, customerId, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChargeUser", reflect.TypeOf((*MockMyService)(nil).ChargeUser), email, customerId, amount)
}

// SendEmail mocks base method.
func (m *MockMyService) SendEmail(recipient, subject, content string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendEmail", recipient, subject, content)
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockMyServiceMockRecorder) SendEmail(recipient, subject, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockMyService)(nil).SendEmail), recipient, subject, content)
}

// UpdateExternalSystem mocks base method.
func (m *MockMyService) UpdateExternalSystem(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateExternalSystem", message)
}

// UpdateExternalSystem indicates an expected call of UpdateExternalSystem.
func (mr *MockMyServiceMockRecorder) UpdateExternalSystem(message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExternalSystem", reflect.TypeOf((*MockMyService)(nil).UpdateExternalSystem), message)
}
